"""
core/models.py
Shared data models used across all components.
All models are immutable (frozen) Pydantic dataclasses.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────────────

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class SignalDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class EventType(str, Enum):
    BAR = "BAR"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"
    PORTFOLIO_UPDATE = "PORTFOLIO_UPDATE"
    RISK_BREACH = "RISK_BREACH"
    SYSTEM = "SYSTEM"


# ─── Market Data ──────────────────────────────────────────────────────────────

class Bar(BaseModel):
    """OHLCV bar for a single instrument."""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: Optional[float] = None

    @property
    def typical_price(self) -> float:
        return (self.high + self.low + self.close) / 3

    @property
    def bar_range(self) -> float:
        return self.high - self.low


# ─── Signals ──────────────────────────────────────────────────────────────────

class Signal(BaseModel):
    """Trading signal generated by a strategy."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    direction: SignalDirection
    strength: float = 1.0          # 0.0 – 1.0, used for position sizing
    strategy_name: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict = Field(default_factory=dict)

    @property
    def is_entry(self) -> bool:
        return self.direction in (SignalDirection.LONG, SignalDirection.SHORT)

    @property
    def is_exit(self) -> bool:
        return self.direction == SignalDirection.FLAT


# ─── Orders ───────────────────────────────────────────────────────────────────

class Order(BaseModel):
    """Order sent to the broker/execution layer."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    side: OrderSide
    order_type: OrderType = OrderType.MARKET
    quantity: float
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    filled_at: Optional[datetime] = None
    filled_price: Optional[float] = None
    filled_quantity: float = 0.0
    signal_id: Optional[str] = None
    strategy_name: str = ""

    @property
    def is_complete(self) -> bool:
        return self.status in (
            OrderStatus.FILLED, OrderStatus.CANCELLED, OrderStatus.REJECTED
        )

    @property
    def commission_estimate(self) -> float:
        """Rough commission estimate before fill."""
        return 0.0  # Populated by execution layer


class Fill(BaseModel):
    """Confirmation of an executed order."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    order_id: str
    symbol: str
    side: OrderSide
    quantity: float
    price: float
    commission: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    @property
    def gross_value(self) -> float:
        return self.quantity * self.price

    @property
    def net_value(self) -> float:
        return self.gross_value + self.commission


# ─── Portfolio ────────────────────────────────────────────────────────────────

class Position(BaseModel):
    """An open position in the portfolio."""
    symbol: str
    quantity: float          # Negative for short
    avg_entry_price: float
    current_price: float = 0.0
    opened_at: datetime = Field(default_factory=datetime.utcnow)
    strategy_name: str = ""
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def cost_basis(self) -> float:
        return abs(self.quantity) * self.avg_entry_price

    @property
    def unrealized_pnl(self) -> float:
        return (self.current_price - self.avg_entry_price) * self.quantity

    @property
    def unrealized_pnl_pct(self) -> float:
        if self.cost_basis == 0:
            return 0.0
        return self.unrealized_pnl / self.cost_basis

    @property
    def is_long(self) -> bool:
        return self.quantity > 0

    @property
    def is_short(self) -> bool:
        return self.quantity < 0


# ─── Events ───────────────────────────────────────────────────────────────────

class Event(BaseModel):
    """Base event passed through the event bus."""
    type: EventType
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    payload: dict = Field(default_factory=dict)
